### PR TITLE
fix: inference of optional properties

### LINKED ISSUE #27: Bug(TypeScript): optional properties inferred as omnipresent
Optional properties are inferred as omnipresent 

```tsx
rpc.register({
  name: 'helloWorld',
  arguments: {
    name: { type: 'string', required: false },
  },
  implementation: async (args, context) => {
    args.name;
    //  ❌  ^? this should be undefined | string
  },
});
```

Currently it is inferred as "string"

### PR DESCRIPTION
**Pull request by KATT**
Closes #27

Also ran prettier which made the diff a bit bigger

### CODE REVIEW

File: javascript/src/types.ts [hunk 1]
```diff
@@ -68,10 +74,18 @@ export type TransformedArgument<TArg extends Argument> = TArg['array'] extends t
...
 /** Represents a map of argument names to argument types. */
-export type TransformedArguments<TArgs extends Arguments> = {
-  [TArg in keyof TArgs]: TransformedArgument<TArgs[TArg]>
-}
+export type TransformedArguments<TArgs extends Arguments> = PartialBy<
+  {
+    [TArg in keyof TArgs]: TransformedArgument<TArgs[TArg]>
+  },
+  GetOptionalArgs<TArgs>
+>
```
Comment (huytool157) [inline javascript/src/types.ts:88]: Clever 👍
